name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    strategy:
      matrix:
        version: [1.13, 1.14, 1.15, 1.16, 1.17, 1.18]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}

    - name: Lint
      run: go vet -v ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
